Add iOS setup
kinecosystem/kin-sdk-unity pull request #22
Opened 2019-08-01 09:16 UTC by Ronserruya

Not a lot of content, just added the steps to use the SDK with iOS

2019-08-01 09:18 UTC, Ronserruya commented
@chaseeb

2019-08-01 14:51 UTC, chaseeb approved these changes

2019-08-04 03:23 UTC, cnotethegr8 requested changes

2019-08-04 03:23 UTC, cnotethegr8 commented on README.md
> +1. You need to have [cocoapods](https://cocoapods.org/) installed
Spelled as 'CocoaPods'. Also add a period to the end of the sentence.

2019-08-04 03:23 UTC, cnotethegr8 commented on README.md
> +To use the the Kin SDK do the following instead:
Remove the second 'the'.

2019-08-04 03:23 UTC, cnotethegr8 commented on README.md
Remove the space between items.

2019-08-04 03:23 UTC, cnotethegr8 commented on README.md
> +2. Run the file ```pods.command``` in the output folder
No need to do a triple \``` just do a single \` on each side. \`pods.command\`

2019-08-04 07:54 UTC, cnotethegr8 approved these changes

2019-08-06 11:08 UTC, merged