Update readme
kinecosystem/kin-sdk-unity pull request #3
Opened 2019-02-19 16:37 UTC by accurateKevin

- Clarify whitelisting process in Unity
- Add links to website documentation
- Language edits

2019-02-19 16:39 UTC, accurateKevin commented
@andreaKin please review.

2019-02-22 18:08 UTC, andreaKin commented
@Ronserruya  and @prime31  Kevin made a number of edits to the Unity intro document based on feedback we received from developers.

Please review, edit and merge as appropriate.

My recommendation is that you then take this and turn it into a new section in the official docs called "Unity". It should be placed after the iOS section and before the Python section so that we have all client SDKs first and all back-end SDKs after.

2019-02-24 08:09 UTC, Ronserruya commented on README.md
> -    account = kinClient.GetAccount( 0 );
The method name was correct, in c# methods names are in CamelCase, unlike java where its "lowerCamelCase"

2019-02-24 08:09 UTC, Ronserruya commented on README.md
> -An optional parameter is `storeKey` which can be used to create a multiple accounts data set,
Why was the section about "storeKey" removed?

2019-02-24 08:11 UTC, Ronserruya commented on README.md
> +At this point in the process your Unity client has created an `account` but the Kin Blockchain does not yet know about it. In the production environment Kin clients are not authorized to create new a
> In the production environment Kin clients are not authorized to create new accounts
Clients cant do it on testnet as well.

And its not the clients are not authorized, the functionality is just not exposed on the client sdk

2019-02-24 08:17 UTC, Ronserruya commented
Added some comments, lets wait for @prime31 to review as well before merging

2019-02-24 08:17 UTC, Ronserruya requested changes
Added some comments, lets wait for @prime31 to review as well before merging

2019-02-25 06:43 UTC, prime31 approved these changes

2019-07-30 11:09 UTC, closed without merging